### ISSUE TITLE
ios version below 9.0 cell did not expand

### ISSUE THREAD

**Issue by coldmn3** [Augustyniak/RATreeView#150]
can't get cell expand on ios 8.2

**Comment by Augustyniak** [comment]
Hey,

Can you provide more information - add code example or explain your use case.

I would also like to encourage you to move to the newest version of the RATreeView. Are there any reasons that prevent you from moving to the newest version?

**Comment by coldmn3** [comment]
i ran the sample on XCode 7.1.1 and set Deployment Target to 8.2, and the cell won't expand on ios 8.2 simulator, please take a look.

**Comment by Amr1977** [comment]
Same issue here, I had to take commit dd48f62 to avoid that (commits after that commit caused cells not to expand in iOS8.4 for me).

**Comment by guylafontaine** [comment]
I have the same Issue, IOS 8.1.3

**Comment by Augustyniak** [comment]
Your issues should be solved by changes made in #154 and are available in version [v2.1.0](https://github.com/Augustyniak/RATreeView/releases/tag/v2.1.0). It would be great if you let me know whether everything works as expected in the [latest release](https://github.com/Augustyniak/RATreeView/releases/tag/v2.1.0).

**Comment by coldmn3** [comment]
i tested ios 7 ~ 8.4 it works perfect now.

**Comment by guylafontaine** [comment]
Thank you, great work

**Comment by Amr1977** [comment]
Issue test pass on iOS 8.4 & 9.1.

(though I still have to use 
```objective-c
if ([self.treeView respondsToSelector:@selector(setCellLayoutMarginsFollowReadableWidth:)]) {
        self.treeView.cellLayoutMarginsFollowReadableWidth = NO;
    }
```
to to make line separators take full width for iPad2 / iOS9.1
)

Thank you very much !

**Comment by jmango360** [comment]
Hi Augustyniak,
i am using the latest version v2.1.0 but the issue still happen on iOS 8.1. The debugger say "[RATableView _configureCellForDisplay:forIndexPath:]". Could u take a look at this issue agains. 
Thanks you!
